// FORGE Wave 6 — Analyst report template.
//
// Renders a Report (title, subtitle, mixed sections) as a clean
// newspaper-style PDF. Section variants: heading (level 1-3),
// commentary (markdown-ish inline tokens), query-result (table).
//
// V1 caveats:
//   - Query-result chart embeds render as the underlying table in the
//     PDF; rasterized chart images need a SVG→PNG pipeline that's a
//     larger lift than this wave.
//   - Inline `code` / **bold** / *italic* tokens are flattened by a
//     small regex pass.

import { View, Text } from '@react-pdf/renderer';
import { BasePDFTemplate } from './BasePDFTemplate';
import { PDFEyebrow } from './components/PDFEyebrow';
import { PDFHeading } from './components/PDFHeading';
import { PDFBody } from './components/PDFBody';
import { PDFTable } from './components/PDFTable';
import type { PDFTableColumn } from './components/PDFTable';
import type { PDFDocumentMeta } from './types';
import type {
  CommentarySection,
  HeadingSection,
  QueryResultSection,
  Report,
  ReportSection,
  SavedQuery,
} from '@/lib/analyst/types';

interface Props {
  report: Report;
  /** Saved queries the report's query-result sections reference. */
  savedQueries: SavedQuery[];
  meta: PDFDocumentMeta;
}

function flattenInline(body: string): string {
  return body
    .replace(/`([^`]+)`/g, '$1')
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/\*([^*]+)\*/g, '$1');
}

export function AnalystReportTemplate({ report, savedQueries, meta }: Props) {
  return (
    <BasePDFTemplate meta={meta}>
      <View>
        <PDFEyebrow variant="hero">ANALYST RESEARCH NOTE</PDFEyebrow>
        <PDFHeading level={1}>{report.title}</PDFHeading>
        {report.subtitle && (
          <PDFHeading level={3} subtitle>
            {report.subtitle}
          </PDFHeading>
        )}
      </View>

      {report.sections.map((section) => (
        <SectionRenderer
          key={section.id}
          section={section}
          savedQueries={savedQueries}
        />
      ))}

      <View style={{ marginTop: 24 }}>
        <PDFEyebrow>METHODOLOGY</PDFEyebrow>
        <PDFBody>
          Generated by GridAlpha Analyst. Query results captured at the
          time of last run for each embedded saved query — see the
          run-time stamps in the Saved Queries library for freshness.
          This report is a decision-support artifact, not investment
          advice.
        </PDFBody>
      </View>

      {/* Keep the `Text` import referenced. */}
      <View style={{ display: 'none' }}>
        <Text>{report.id}</Text>
      </View>
    </BasePDFTemplate>
  );
}

// ─── Section dispatcher ──────────────────────────────────────────

function SectionRenderer({
  section,
  savedQueries,
}: {
  section: ReportSection;
  savedQueries: SavedQuery[];
}) {
  switch (section.kind) {
    case 'heading':
      return <HeadingRenderer section={section as HeadingSection} />;
    case 'commentary':
      return <CommentaryRenderer section={section as CommentarySection} />;
    case 'query-result':
      return (
        <QueryResultRenderer
          section={section as QueryResultSection}
          savedQueries={savedQueries}
        />
      );
  }
}

function HeadingRenderer({ section }: { section: HeadingSection }) {
  return (
    <View style={{ marginTop: 18 }}>
      <PDFHeading level={section.level}>{section.text || 'Untitled'}</PDFHeading>
    </View>
  );
}

function CommentaryRenderer({ section }: { section: CommentarySection }) {
  if (!section.body.trim()) return null;
  const paragraphs = section.body.split(/\n\s*\n/);
  return (
    <View style={{ marginTop: 10 }}>
      {paragraphs.map((p, i) => (
        <PDFBody key={i}>{flattenInline(p)}</PDFBody>
      ))}
    </View>
  );
}

function QueryResultRenderer({
  section,
  savedQueries,
}: {
  section: QueryResultSection;
  savedQueries: SavedQuery[];
}) {
  const query = savedQueries.find((q) => q.id === section.savedQueryId);
  const result = query?.lastResult;
  if (!query || !result) {
    return (
      <View style={{ marginTop: 14 }}>
        <PDFEyebrow>QUERY RESULT (UNRESOLVED)</PDFEyebrow>
        <PDFBody>
          Embedded query not yet run. Run the saved query before exporting.
        </PDFBody>
      </View>
    );
  }
  const cols: PDFTableColumn[] = result.schema.map((c) => ({
    label: c.label.toUpperCase(),
    flex: 1,
    align: c.type === 'number' ? 'right' : 'left',
  }));
  const rows: (string | number)[][] = result.rows.slice(0, 60).map((r) =>
    result.schema.map((c) => {
      const v = r[c.key];
      if (v === null || v === undefined) return '—';
      if (typeof v === 'number') {
        if (c.format?.startsWith('$')) return `$${v.toFixed(2)}`;
        if (c.format?.includes('%')) return `${v.toFixed(1)}%`;
        return v.toLocaleString(undefined, { maximumFractionDigits: 2 });
      }
      return String(v);
    }),
  );
  return (
    <View break style={{ marginTop: 14 }}>
      <PDFEyebrow>{query.name.toUpperCase()}</PDFEyebrow>
      {section.caption && <PDFBody>{section.caption}</PDFBody>}
      <PDFTable columns={cols} rows={rows} />
    </View>
  );
}
