"""ORM models — world country energy profiles (Cursor Wave 10).

Source: Our World in Data energy dataset
(https://github.com/owid/energy-data), real dataset with 130 columns as of
this wave's audit (the brief's "134" is stale — OWID revises the dataset on
its own cadence; reported as measured, not corrected to match the brief).

FIELD_DEFINITIONS is the single source of truth for the 12 ingested metric
columns. Every entry is copied verbatim from the real codebook
(``owid-energy-codebook.csv``, fetched from
``https://raw.githubusercontent.com/owid/energy-data/master/owid-energy-codebook.csv``
— the URL in the brief, ``owid-public.owid.io/.../owid-energy-codebook.csv``,
404s; the JSON data URL in the brief is correct and unrelated). No citation
or unit here was invented — both the ingest script and
``country_energy_field_source`` read from this same list, so the schema and
the API can never drift from what the codebook actually says.

Field selection (Fase 1), mapped to the brief's requested shape:
  - matriz por combustível: fossil_share_elec, nuclear_share_elec,
    hydro_share_elec, wind_share_elec, solar_share_elec, biofuel_share_elec,
    other_renewables_share_elec_exc_biofuel (excludes bioenergy so it does
    not double-count against biofuel_share_elec)
  - geração total: electricity_generation
  - participação de renovável: renewables_share_elec
  - intensidade de carbono: carbon_intensity_elec
  - consumo per capita: energy_per_capita (primary energy, not just
    electricity — deliberately broader than the generation figure)
  - population: kept as context, not part of the brief's explicit list, but
    required to make any "per capita" figure interpretable without a second
    lookup.

Deliberately NOT ingested: per-fuel sub-splits of "fossil" (coal/gas/oil
electricity shares), and the *_share_energy (primary-energy-basis) variants
of the same fuels — the brief asks for the aggregated matrix, not the full
134(130)-column surface, and the *_share_elec variants (Ember-sourced) have
materially better country coverage in the most recent year than the
*_share_energy (Energy Institute-sourced) ones, which cover roughly the
~90 countries Energy Institute reports on rather than the full sovereign set.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import BigInteger, DateTime, Integer, Numeric, Text, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base

# (column_name, sqlalchemy type ctor, title, unit, source_citation)
# unit/source_citation are copied verbatim from owid-energy-codebook.csv.
FIELD_DEFINITIONS: list[dict[str, str]] = [
    {
        "column": "population",
        "title": "Population",
        "unit": "people",
        "source_citation": (
            "Population based on various sources (2024) "
            "[https://ourworldindata.org/population-sources]"
        ),
    },
    {
        "column": "electricity_generation",
        "title": "Total electricity generation",
        "unit": "terawatt-hours (TWh)",
        "source_citation": (
            "Ember - Yearly Electricity Data Europe (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]; "
            "Ember - Yearly Electricity Data (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]; "
            "Energy Institute - Statistical Review of World Energy (2025) "
            "[https://www.energyinst.org/statistical-review/]"
        ),
    },
    {
        "column": "renewables_share_elec",
        "title": "Share of electricity generated by renewables",
        "unit": "%",
        "source_citation": (
            "Ember - Yearly Electricity Data Europe (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]; "
            "Ember - Yearly Electricity Data (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]; "
            "Energy Institute - Statistical Review of World Energy (2025) "
            "[https://www.energyinst.org/statistical-review/]"
        ),
    },
    {
        "column": "carbon_intensity_elec",
        "title": "Lifecycle carbon intensity of electricity generation",
        "unit": "grams of CO\u2082 equivalents per kilowatt-hour (gCO\u2082)",
        "source_citation": (
            "Ember - Yearly Electricity Data Europe (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]; "
            "Ember - Yearly Electricity Data (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]"
        ),
    },
    {
        "column": "energy_per_capita",
        "title": "Primary energy consumption per capita",
        "unit": "kilowatt-hours per person (kWh)",
        "source_citation": (
            "U.S. Energy Information Administration - International Energy Data (2025) "
            "[https://www.eia.gov/opendata/bulkfiles.php]; "
            "Energy Institute - Statistical Review of World Energy (2025) "
            "[https://www.energyinst.org/statistical-review/]; "
            "Population based on various sources (2024) "
            "[https://ourworldindata.org/population-sources]"
        ),
    },
    {
        "column": "fossil_share_elec",
        "title": "Share of electricity generated by fossil fuels",
        "unit": "%",
        "source_citation": (
            "Ember - Yearly Electricity Data Europe (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]; "
            "Ember - Yearly Electricity Data (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]; "
            "Energy Institute - Statistical Review of World Energy (2025) "
            "[https://www.energyinst.org/statistical-review/]"
        ),
    },
    {
        "column": "nuclear_share_elec",
        "title": "Share of electricity generated by nuclear power",
        "unit": "%",
        "source_citation": (
            "Ember - Yearly Electricity Data Europe (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]; "
            "Ember - Yearly Electricity Data (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]; "
            "Energy Institute - Statistical Review of World Energy (2025) "
            "[https://www.energyinst.org/statistical-review/]"
        ),
    },
    {
        "column": "hydro_share_elec",
        "title": "Share of electricity generated by hydropower",
        "unit": "%",
        "source_citation": (
            "Ember - Yearly Electricity Data Europe (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]; "
            "Ember - Yearly Electricity Data (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]; "
            "Energy Institute - Statistical Review of World Energy (2025) "
            "[https://www.energyinst.org/statistical-review/]"
        ),
    },
    {
        "column": "wind_share_elec",
        "title": "Share of electricity generated by wind power",
        "unit": "%",
        "source_citation": (
            "Ember - Yearly Electricity Data Europe (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]; "
            "Ember - Yearly Electricity Data (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]; "
            "Energy Institute - Statistical Review of World Energy (2025) "
            "[https://www.energyinst.org/statistical-review/]"
        ),
    },
    {
        "column": "solar_share_elec",
        "title": "Share of electricity generated by solar power",
        "unit": "%",
        "source_citation": (
            "Ember - Yearly Electricity Data Europe (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]; "
            "Ember - Yearly Electricity Data (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]; "
            "Energy Institute - Statistical Review of World Energy (2025) "
            "[https://www.energyinst.org/statistical-review/]"
        ),
    },
    {
        "column": "biofuel_share_elec",
        "title": "Share of electricity generated by bioenergy",
        "unit": "%",
        "source_citation": (
            "Ember - Yearly Electricity Data Europe (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]; "
            "Ember - Yearly Electricity Data (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]; "
            "Energy Institute - Statistical Review of World Energy (2025) "
            "[https://www.energyinst.org/statistical-review/]"
        ),
    },
    {
        "column": "other_renewables_share_elec_exc_biofuel",
        "title": "Share of electricity generated by other renewables, excluding bioenergy",
        "unit": "%",
        "source_citation": (
            "Ember - Yearly Electricity Data Europe (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]; "
            "Ember - Yearly Electricity Data (2026) "
            "[https://ember-energy.org/data/yearly-electricity-data/]; "
            "Energy Institute - Statistical Review of World Energy (2025) "
            "[https://www.energyinst.org/statistical-review/]"
        ),
    },
]

FIELD_NAMES: tuple[str, ...] = tuple(f["column"] for f in FIELD_DEFINITIONS)


class CountryEnergyProfile(Base):
    __tablename__ = "country_energy_profile"
    __table_args__ = (UniqueConstraint("iso_code", name="country_energy_profile_iso_code_key"),)

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )
    iso_code: Mapped[str] = mapped_column(Text, nullable=False)
    country_name: Mapped[str] = mapped_column(Text, nullable=False)
    year: Mapped[int] = mapped_column(Integer, nullable=False)

    population: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    electricity_generation: Mapped[float | None] = mapped_column(Numeric(14, 4), nullable=True)
    renewables_share_elec: Mapped[float | None] = mapped_column(Numeric(6, 3), nullable=True)
    carbon_intensity_elec: Mapped[float | None] = mapped_column(Numeric(9, 3), nullable=True)
    energy_per_capita: Mapped[float | None] = mapped_column(Numeric(12, 3), nullable=True)
    fossil_share_elec: Mapped[float | None] = mapped_column(Numeric(6, 3), nullable=True)
    nuclear_share_elec: Mapped[float | None] = mapped_column(Numeric(6, 3), nullable=True)
    hydro_share_elec: Mapped[float | None] = mapped_column(Numeric(6, 3), nullable=True)
    wind_share_elec: Mapped[float | None] = mapped_column(Numeric(6, 3), nullable=True)
    solar_share_elec: Mapped[float | None] = mapped_column(Numeric(6, 3), nullable=True)
    biofuel_share_elec: Mapped[float | None] = mapped_column(Numeric(6, 3), nullable=True)
    other_renewables_share_elec_exc_biofuel: Mapped[float | None] = mapped_column(
        Numeric(6, 3), nullable=True
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class CountryEnergyFieldSource(Base):
    """One row per ingested metric column — citation + unit for the API to serve.

    Population and the eleven mix/generation/intensity/per-capita metrics
    all get a row; ``iso_code``/``country_name``/``year`` are keys, not
    metrics, so they are not represented here.
    """

    __tablename__ = "country_energy_field_source"

    field_name: Mapped[str] = mapped_column(Text, primary_key=True)
    source_citation: Mapped[str] = mapped_column(Text, nullable=False)
    unit: Mapped[str] = mapped_column(Text, nullable=False)
