import { GeoJsonLayer } from '@deck.gl/layers';

/**
 * LMP color interpolator: Electric Blue [0,163,255] → Cyan Pulse [0,255,240]
 * Maps 0–200 $/MWh price range to the GridAlpha V2 color vocabulary.
 */
const getLmpColor = (lmp: number): [number, number, number] => {
  const t = Math.min(Math.max(lmp / 200, 0), 1);
  const g = Math.round(163 + t * (255 - 163));
  const b = Math.round(255 - t * (255 - 240));
  return [0, g, b];
};

/**
 * Creates the deck.gl GeoJsonLayer for PJM zone extrusions.
 * Extrusion height uses logarithmic scaling of LMP to prevent extreme spikes.
 * Base height 200m ensures zones always visible; 800 multiplier keeps
 * extrusions grounded at the current zoom level.
 * Generated by Gemini (Spatial Math Engine) — Phase 3.
 */
export const createPjmZoneLayer = (
  pjmGeoJsonData: GeoJSON.FeatureCollection,
  hoveredZoneId: string | null,
  selectedZoneId: string | null
) => {
  return new GeoJsonLayer({
    id: 'pjm-zones-extruded',
    data: pjmGeoJsonData,
    pickable: true,
    extruded: true,
    stroked: true,
    filled: true,
    wireframe: true,
    getElevation: (d: GeoJSON.Feature) => {
      const lmp = (d.properties?.lmp_total as number) || 1;
      return Math.log10(Math.max(lmp, 1)) * 800 + 200;
    },
    getFillColor: (d: GeoJSON.Feature) => {
      const baseColor = getLmpColor((d.properties?.lmp_total as number) || 0);
      const zoneId = d.properties?.zone_id;
      let alpha = 210;
      if (zoneId === selectedZoneId) alpha = 255;
      else if (zoneId === hoveredZoneId) alpha = 245;
      return [...baseColor, alpha] as [number, number, number, number];
    },
    getLineColor: [0, 255, 240, 255] as [number, number, number, number],
    lineWidthMinPixels: 1,
    updateTriggers: {
      getFillColor: [hoveredZoneId, selectedZoneId],
      getElevation: [pjmGeoJsonData]
    },
    transitions: {
      getElevation: 400,
      getFillColor: 200
    }
  });
};
